# File/folder paths
paths:
  bop_parent_path: 'resources/bop_data'
  lablight_models_path: 'resources/specprep_models'
  cc_textures_path: 'resources/cc_textures'
  output_dir: 'output/'

# Output BOP and/or COCO format annotations
outputs:
  coco_annotations: False
  bop_annotations: True

# Select specific models to render ([obj1.obj, obj2.obj]). Leave list empty to render all models from 'lablight_models_path'.
specific_models: ['micropipette_mm.obj']

# Number of samples
samples_per_scene: 20 # N times Camera sampling from same scene
scenes_to_sample: 1 # Generating new scene and dropping new objects

# Numbers of objects to sample per scene
n_distractors: 2 # distractor LineMod objects
n_objects: 1 # Lablight's objects
sample_n_object: False # If true, this will sample between [1, n_objects] number of objects. If False, this will render exactly n_objects in each scene.

# Light energy values to sample between
light:
  min_energy: 10 # watts
  max_energy: 100 # watts

# Camera angles and distance to objects to sample between
camera:
  elevation_min: 70 # angle of elevation in degrees [-90,90]
  elevation_max: 90 # angle of elevation in degrees [-90,90]
  radius_min: 0.2 # meters
  radius_max: 0.6 # meters   